services:
  api:
    build: .
    restart: always
    env_file:
      - ./.env
    expose:
      - "8000"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: always
    expose:
      - "6379"

  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" # Dla HTTP/3
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api

volumes:
  caddy_data:
  caddy_config: