"""Create rally table

Revision ID: 124928f349ba
Revises: f234c3ba33d9
Create Date: 2025-09-01 12:50:57.701014

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "124928f349ba"
down_revision: Union[str, None] = "f234c3ba33d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rally",
        sa.Column("rally_number_in_set", sa.Integer(), nullable=False),
        sa.Column("raw_rally_code", sa.String(length=256), nullable=True),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("set_id", sa.Uuid(), nullable=False),
        sa.Column("serve_team_id", sa.Uuid(), nullable=False),
        sa.Column("score_team_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("rally_number_in_set > 0", name="ck_rally_number_positive"),
        sa.ForeignKeyConstraint(
            ["score_team_id"],
            ["team.id"],
        ),
        sa.ForeignKeyConstraint(
            ["serve_team_id"],
            ["team.id"],
        ),
        sa.ForeignKeyConstraint(
            ["set_id"],
            ["set.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "set_id", "rally_number_in_set", name="uq_set_rally_number"
        ),
    )
    op.create_index(
        op.f("ix_rally_raw_rally_code"), "rally", ["raw_rally_code"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rally_raw_rally_code"), table_name="rally")
    op.drop_table("rally")
    # ### end Alembic commands ###
