"""Adjust user role column type

Revision ID: 384d843d817b
Revises: f0cd843a3a75
Create Date: 2025-08-16 23:02:50.577653

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "384d843d817b"
down_revision: Union[str, None] = "f0cd843a3a75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "role",
        existing_type=sa.VARCHAR(),
        nullable=True,
        existing_server_default=sa.text("'user'::character varying"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "role",
        existing_type=sa.VARCHAR(),
        nullable=False,
        existing_server_default=sa.text("'user'::character varying"),
    )
    # ### end Alembic commands ###
