"""Create action table

Revision ID: 4aa3502cc54a
Revises: 124928f349ba
Create Date: 2025-09-02 10:12:08.467964

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4aa3502cc54a"
down_revision: Union[str, None] = "124928f349ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "action",
        sa.Column("sequence_in_rally", sa.Integer(), nullable=False),
        sa.Column("raw_action_code", sa.String(length=64), nullable=True),
        sa.Column("team_context", sa.CHAR(length=1), nullable=True),
        sa.Column("skill_code", sa.CHAR(length=1), nullable=True),
        sa.Column("evaluation_code", sa.CHAR(length=1), nullable=True),
        sa.Column("player_jersey_number", sa.Integer(), nullable=True),
        sa.Column("start_zone", sa.Integer(), nullable=True),
        sa.Column("end_zone", sa.Integer(), nullable=True),
        sa.Column("start_subzone", sa.CHAR(length=1), nullable=True),
        sa.Column("end_subzone", sa.CHAR(length=1), nullable=True),
        sa.Column(
            "modifiers", sqlmodel.sql.sqltypes.AutoString(length=12), nullable=True
        ),
        sa.Column("rally_id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("end_subzone ~ '^[A-I]$'", name="ck_end_subzone_valid_char"),
        sa.CheckConstraint(
            "start_subzone ~ '^[A-I]$'", name="ck_start_subzone_valid_char"
        ),
        sa.CheckConstraint("end_zone >= 1 AND end_zone <= 9", name="ck_end_zone_range"),
        sa.CheckConstraint("sequence_in_rally > 0", name="ck_action_sequence_positive"),
        sa.CheckConstraint(
            "start_zone >= 1 AND start_zone <= 9", name="ck_start_zone_range"
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rally_id"],
            ["rally.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rally_id", "sequence_in_rally", name="uq_rally_sequence"),
    )
    op.create_index(
        op.f("ix_action_raw_action_code"), "action", ["raw_action_code"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_action_raw_action_code"), table_name="action")
    op.drop_table("action")
    # ### end Alembic commands ###
