"""Add lineup table

Revision ID: 4fe692d306e5
Revises: 64b0163216f3
Create Date: 2026-02-17 22:25:21.233333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4fe692d306e5'
down_revision: Union[str, None] = '64b0163216f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineup',
    sa.Column('set_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('p1_id', sa.Uuid(), nullable=False),
    sa.Column('p2_id', sa.Uuid(), nullable=False),
    sa.Column('p3_id', sa.Uuid(), nullable=False),
    sa.Column('p4_id', sa.Uuid(), nullable=False),
    sa.Column('p5_id', sa.Uuid(), nullable=False),
    sa.Column('p6_id', sa.Uuid(), nullable=False),
    sa.Column('libero_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['libero_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['p1_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['p2_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['p3_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['p4_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['p5_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['p6_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['set.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('refresh_token', 'jti',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.drop_index(op.f('ix_refresh_token_expires_at'), table_name='refresh_token')
    op.drop_index(op.f('ix_refresh_token_user_id'), table_name='refresh_token')
    op.drop_index(op.f('ix_refresh_token_user_id_revoked'), table_name='refresh_token')
    op.drop_constraint(op.f('refresh_token_user_id_fkey'), 'refresh_token', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_token', 'user', ['user_id'], ['id'])
    op.alter_column('special_event', 'event_type',
               existing_type=postgresql.ENUM('timeout', 'substitution', 'card', 'challenge', 'other', name='specialeventtype'),
               nullable=True)
    op.alter_column('special_event', 'raw_special_code',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_index(op.f('ix_special_event_raw_code'), table_name='special_event')
    op.create_index(op.f('ix_special_event_raw_special_code'), 'special_event', ['raw_special_code'], unique=False)
    op.drop_constraint(op.f('special_event_player_id_fkey'), 'special_event', type_='foreignkey')
    op.drop_constraint(op.f('special_event_match_id_fkey'), 'special_event', type_='foreignkey')
    op.drop_constraint(op.f('special_event_team_id_fkey'), 'special_event', type_='foreignkey')
    op.drop_constraint(op.f('special_event_set_id_fkey'), 'special_event', type_='foreignkey')
    op.create_foreign_key(None, 'special_event', 'set', ['set_id'], ['id'])
    op.create_foreign_key(None, 'special_event', 'match', ['match_id'], ['id'])
    op.create_foreign_key(None, 'special_event', 'team', ['team_id'], ['id'])
    op.create_foreign_key(None, 'special_event', 'player', ['player_id'], ['id'])
    op.drop_index(op.f('ix_users_email'), table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index(op.f('ix_users_email'), 'user', ['email'], unique=True)
    op.drop_constraint(None, 'special_event', type_='foreignkey')
    op.drop_constraint(None, 'special_event', type_='foreignkey')
    op.drop_constraint(None, 'special_event', type_='foreignkey')
    op.drop_constraint(None, 'special_event', type_='foreignkey')
    op.create_foreign_key(op.f('special_event_set_id_fkey'), 'special_event', 'set', ['set_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('special_event_team_id_fkey'), 'special_event', 'team', ['team_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('special_event_match_id_fkey'), 'special_event', 'match', ['match_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('special_event_player_id_fkey'), 'special_event', 'player', ['player_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_special_event_raw_special_code'), table_name='special_event')
    op.create_index(op.f('ix_special_event_raw_code'), 'special_event', ['raw_special_code'], unique=False)
    op.alter_column('special_event', 'raw_special_code',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('special_event', 'event_type',
               existing_type=postgresql.ENUM('timeout', 'substitution', 'card', 'challenge', 'other', name='specialeventtype'),
               nullable=False)
    op.drop_constraint(None, 'refresh_token', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_token_user_id_fkey'), 'refresh_token', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_refresh_token_user_id_revoked'), 'refresh_token', ['user_id', 'revoked_at'], unique=False)
    op.create_index(op.f('ix_refresh_token_user_id'), 'refresh_token', ['user_id'], unique=False)
    op.create_index(op.f('ix_refresh_token_expires_at'), 'refresh_token', ['expires_at'], unique=False)
    op.alter_column('refresh_token', 'jti',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_table('lineup')
    # ### end Alembic commands ###
