"""Create match table

Revision ID: 8b0a14b052e2
Revises: c5fca641f687
Create Date: 2025-08-31 11:53:50.924276

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b0a14b052e2"
down_revision: Union[str, None] = "c5fca641f687"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "match",
        sa.Column("match_date", sa.Date(), nullable=True),
        sa.Column("spectators", sa.Integer(), nullable=True),
        sa.Column("home_team_score", sa.Integer(), nullable=True),
        sa.Column("away_team_score", sa.Integer(), nullable=True),
        sa.Column("season_id", sa.Uuid(), nullable=False),
        sa.Column("home_team_id", sa.Uuid(), nullable=False),
        sa.Column("away_team_id", sa.Uuid(), nullable=False),
        sa.Column("winner_team_id", sa.Uuid(), nullable=True),
        sa.Column("arena_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["arena_id"],
            ["arena.id"],
        ),
        sa.ForeignKeyConstraint(
            ["away_team_id"],
            ["team.id"],
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"],
            ["team.id"],
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["season.id"],
        ),
        sa.ForeignKeyConstraint(
            ["winner_team_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("match")
    # ### end Alembic commands ###
