"""Add score snapshots to rally

Revision ID: aabc82f9c83a
Revises: c697359fba76
Create Date: 2026-02-18 22:11:07.888633

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aabc82f9c83a'
down_revision: Union[str, None] = 'c697359fba76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'rally',
        sa.Column(
            'home_score_snapshot',
            sa.Integer(),
            nullable=False,
            server_default='0')
    )
    op.add_column(
        'rally',
        sa.Column(
            'away_score_snapshot',
            sa.Integer(),
            nullable=False,
            server_default='0'
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rally', 'away_score_snapshot')
    op.drop_column('rally', 'home_score_snapshot')
    # ### end Alembic commands ###
