"""action: add indexes, relax null checks, set modifiers length

Revision ID: b34613bcbb4f
Revises: 4aa3502cc54a
Create Date: 2025-09-29 18:57:01.045747

"""

from collections.abc import Sequence
from typing import Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b34613bcbb4f"
down_revision: Union[str, None] = "4aa3502cc54a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_action_player_id", "action", ["player_id"], unique=False)
    op.create_index("ix_action_rally_id", "action", ["rally_id"], unique=False)
    op.create_index(
        "ix_action_rally_seq", "action", ["rally_id", "sequence_in_rally"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_action_rally_seq", table_name="action")
    op.drop_index("ix_action_rally_id", table_name="action")
    op.drop_index("ix_action_player_id", table_name="action")
    # ### end Alembic commands ###
