"""Add set_state and live tables

Revision ID: c697359fba76
Revises: 4fe692d306e5
Create Date: 2026-02-18 20:10:13.991209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c697359fba76'
down_revision: Union[str, None] = '4fe692d306e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('set_state',
    sa.Column('serving_team_id', sa.Uuid(), nullable=False),
    sa.Column('serving_index', sa.Integer(), nullable=False),
    sa.Column('rotation_home', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('rotation_away', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('libero_home_id', sa.Uuid(), nullable=True),
    sa.Column('libero_away_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('set_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['serving_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['set.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('set_id', name='uq_set_state_set_id')
    )
    op.create_index(op.f('ix_set_state_set_id'), 'set_state', ['set_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_set_state_set_id'), table_name='set_state')
    op.drop_table('set_state')
    # ### end Alembic commands ###
